Experiment No: 7

Title: Implement an LSTM Autoencoder Model

Aim:

To implement an LSTM-based autoencoder model for learning efficient representations of sequential data and reconstructing the input sequences.

Procedure:

1.Import Libraries
Import TensorFlow/Keras, NumPy, and required modules.

2.Prepare Dataset
Create or load sequential data (time-series or sequence data).

3.Preprocess Data
Normalize and reshape the data into 3D format (samples, timesteps, features).

4.Build Encoder
Add LSTM layer(s) to encode input sequences into a compressed representation.

5.Build Decoder
Add RepeatVector and LSTM layers to reconstruct the original sequence.

6.Add Output Layer
Use TimeDistributed Dense layer to generate output sequence.

7.Compile Model
Use optimizer (Adam) and loss function (MSE).

8.Train Model
Train the autoencoder using input data as both input and output.

9.Evaluate Model
Compare reconstructed output with original input.

In [1]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, RepeatVector, TimeDistributed, Dense

# Sample sequential data
data = np.array([
    [[1], [2], [3]],
    [[2], [3], [4]],
    [[3], [4], [5]],
    [[4], [5], [6]]
])

# Define model
timesteps = 3
features = 1

inputs = Input(shape=(timesteps, features))

# Encoder
encoded = LSTM(64, activation='relu')(inputs)

# Repeat vector
decoded = RepeatVector(timesteps)(encoded)

# Decoder
decoded = LSTM(64, activation='relu', return_sequences=True)(decoded)

# Output layer
outputs = TimeDistributed(Dense(1))(decoded)

# Autoencoder model
model = Model(inputs, outputs)

# Compile
model.compile(optimizer='adam', loss='mse')

# Train
model.fit(data, data, epochs=200, verbose=0)

# Test reconstruction
reconstructed = model.predict(data)

print("Original Data:\n", data)
print("\nReconstructed Data:\n", reconstructed)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step
Original Data:
 [[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[4]
  [5]
  [6]]]

Reconstructed Data:
 [[[1.3013604]
  [2.1127899]
  [2.6865845]]

 [[2.0068018]
  [3.0736587]
  [3.793435 ]]

 [[2.9108536]
  [4.0866575]
  [4.9296055]]

 [[4.026246 ]
  [5.057068 ]
  [6.069652 ]]]


Result:

Successfully implemented an LSTM autoencoder model. The model effectively learned compressed representations of sequential data and reconstructed the input sequences with minimal loss.