**Exp No:2**

Title: Implementation of different tensor types


Aim:
To study and implement different types of tensors used in deep learning and understand their properties and operations.

Procedure:

1.Import Library
Import TensorFlow or NumPy library to work with tensors.

2.Create Scalars (0D Tensor)
Define a single numerical value.

3.Create Vectors (1D Tensor)
Create a list or array of values.

4.Create Matrices (2D Tensor)
Define a 2D array with rows and columns.

5.Create Higher-Dimensional Tensors
Create tensors with 3 or more dimensions.

6.Perform Basic Operations
Perform operations like addition, multiplication, and reshaping.

7.Check Tensor Properties
Analyze shape, datatype, and dimensions of tensors.

In [1]:
import tensorflow as tf

# Scalar (0D tensor)
scalar = tf.constant(10)
print("Scalar:", scalar)

# Vector (1D tensor)
vector = tf.constant([1, 2, 3, 4])
print("Vector:", vector)

# Matrix (2D tensor)
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# 3D Tensor
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor:\n", tensor_3d)

# Tensor operations
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print("Addition:", tf.add(a, b))
print("Multiplication:", tf.multiply(a, b))

# Shape and dimension
print("Shape of matrix:", matrix.shape)
print("Dimensions of 3D tensor:", tensor_3d.ndim)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Shape of matrix: (2, 2)
Dimensions of 3D tensor: 3


Result:

Successfully implemented different tensor types including scalar, vector, matrix, and higher-dimensional tensors. Basic tensor operations and properties were also verified using TensorFlow.